index:
   path: /
   controller: App\Controller\HomeController::home

recipe:
   path: /recipe
   controller: App\Controller\RecipeController::recipe

results:
    path: /results
    controller: App\Controller\ResultsController::results