index:
   path: /
   controller: App\Controller\HomeController::home

recipe:
   path: /recipe
   controller: App\Controller\RecipeController::recipe

results:
    path: /results
    controller: App\Controller\ResultsController::results

save-recipe:
    path: /save-recipe
    controller: App\Controller\SaveRecipeController::saveRecipeGet

category:
    path: /category
    controller: App\Controller\CategoryController::category  

save:
    path: /saved
    controller: App\Controller\SaveRecipeController::saveRecipePost    